`RABBITMQ_HEARTBEAT` Fix (#82)
Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -67,11 +67,10 @@ jobs:
 
   example:
     needs: [py-versions]
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-20.04, ubuntu-22.04]
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
         broker_client: [gcp, nats, pulsar, rabbitmq]
     steps:
@@ -81,6 +80,9 @@ jobs:
           python-version: ${{ matrix.py3 }}
       - name: example
         run: |
+          # NOTE: these examples are intended to be the most basic in terms of config:
+          #   no auth, no unnecessary env vars, etc.
+
           # Pulsar
           if [ "${{ matrix.broker_client }}" = "pulsar" ]; then
             ./resources/docker-pulsar.sh "${{ matrix.broker_client }}"
@@ -91,7 +93,6 @@ jobs:
           elif [ "${{ matrix.broker_client }}" = "gcp" ]; then
             export PUBSUB_EMULATOR_HOST=localhost:8085
             ./resources/local-gcp-emulator.sh
-            sleep 15
           # NATS
           elif [ "${{ matrix.broker_client }}" = "nats" ]; then
             ./resources/local-nats-js.sh
@@ -102,8 +103,26 @@ jobs:
 
           pip install --upgrade pip wheel setuptools
           pip install .[dev,${{ matrix.broker_client }}]
-          python examples/worker.py --broker-client ${{ matrix.broker_client }} >> worker.out 2>&1 &
-          python examples/server.py --broker-client ${{ matrix.broker_client }}
+
+          while true; do  # auto-retry for GCP (it fails to start up in time, often & undeterministically)
+            id=$(date +%s)
+            python examples/worker.py \
+                --broker-client ${{ matrix.broker_client }} \
+                --in-queue "queue1-$id" \
+                --out-queue "queue2-$id" \
+                >> worker.out 2>&1 &
+            failed=no
+            python examples/server.py \
+                --broker-client ${{ matrix.broker_client }} \
+                --work-queue "queue1-$id" \
+                --result-queue "queue2-$id" \
+                || failed=yes
+            if [ "$failed" = "yes" ] && [ "${{ matrix.broker_client }}" = "gcp" ]; then
+              sleep 15
+              continue
+            fi
+            break
+          done
 
       - name: worker output
         if: always()
@@ -127,11 +146,10 @@ jobs:
 
   unit-test:
     needs: [py-versions]
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-20.04, ubuntu-22.04]
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
         type: [brokerless, pulsar, rabbitmq]
     steps:
@@ -151,11 +169,10 @@ jobs:
 
   integration-test:
     needs: [py-versions]
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-20.04, ubuntu-22.04]
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
         broker_client: [gcp, nats, pulsar, rabbitmq]
     services:
@@ -210,6 +227,7 @@ jobs:
           elif [ "${{ matrix.broker_client }}" = "rabbitmq" ]; then
             ./resources/docker-rabbitmq.sh "${{ matrix.broker_client }}" ./resources/rabbitmq-custom.conf
             export PYTEST_DO_AUTH_FOR_MQCLIENT=yes
+            export RABBITMQ_HEARTBEAT=60
           # GCP
           elif [ "${{ matrix.broker_client }}" = "gcp" ]; then
             export PUBSUB_EMULATOR_HOST=localhost:8085
