examples: auto-retry for GCP

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -94,7 +94,6 @@ jobs:
           elif [ "${{ matrix.broker_client }}" = "gcp" ]; then
             export PUBSUB_EMULATOR_HOST=localhost:8085
             ./resources/local-gcp-emulator.sh
-            sleep 15
           # NATS
           elif [ "${{ matrix.broker_client }}" = "nats" ]; then
             ./resources/local-nats-js.sh
@@ -105,8 +104,17 @@ jobs:
 
           pip install --upgrade pip wheel setuptools
           pip install .[dev,${{ matrix.broker_client }}]
-          python examples/worker.py --broker-client ${{ matrix.broker_client }} >> worker.out 2>&1 &
-          python examples/server.py --broker-client ${{ matrix.broker_client }}
+
+          while true; do  # auto-retry for GCP (it fails to start up in time, often & undeterministically)
+            python examples/worker.py --broker-client ${{ matrix.broker_client }} >> worker.out 2>&1 &
+            failed=no
+            python examples/server.py --broker-client ${{ matrix.broker_client }} || failed=yes
+            if [ "$failed" = "yes" ] && [ "${{ matrix.broker_client }}" = "gcp" ]; then
+              sleep 15
+              continue
+            fi
+            break
+          done
 
       - name: worker output
         if: always()
