Check if the Keycloak container is running before boostrap

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -92,7 +92,7 @@ jobs:
       - name: example
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           # NOTE: these examples are intended to be the most basic in terms of config:
           #   no auth, no unnecessary env vars, etc.
 
@@ -128,14 +128,14 @@ jobs:
         if: always()
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           cat worker.out
 
       - name: broker output
         if: always()
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           set -x
           cat ./broker.out
           if [ -n "$(ls -A ./broker_logs/ 2>/dev/null)" ]; then
@@ -147,7 +147,7 @@ jobs:
         if: always()
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker logs "${{ matrix.broker_client }}" || true
 
   unit-test:
@@ -166,7 +166,7 @@ jobs:
       - name: tests
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           pip install --upgrade pip wheel setuptools
           if [ "${{ matrix.type }}" = "brokerless" ]; then
             pip install .[dev]
@@ -209,21 +209,29 @@ jobs:
       - name: install deps
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           pip install --upgrade pip wheel setuptools
           pip install .[dev,${{ matrix.broker_client }},integration]
       - name: get keycloak cert
         if: matrix.broker_client == 'rabbitmq'
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker run --rm -v $PWD:/mnt -u root --entrypoint=/usr/bin/keytool ghcr.io/wipacrepo/keycloak-rest-services:test-keycloak-master -export -alias server -keystore /opt/keycloak/conf/server.keystore -rfc -file /mnt/public.cert -storepass password
           echo "REQUESTS_CA_BUNDLE=$PWD/public.cert" >> $GITHUB_ENV
       - name: bootstrap keycloak
         if: matrix.broker_client == 'rabbitmq'
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          
+          # Check if the Keycloak container is running before boostrap
+          KEYCLOAK_CONTAINER=$(docker ps --filter "ancestor=ghcr.io/wipacrepo/keycloak-rest-services:test-keycloak-master" --format "{{.Names}}" | head -n 1)
+          if [ -z "$KEYCLOAK_CONTAINER" ]; then
+            echo "::error::Keycloak container is not running!"
+            exit 1
+          fi
+
           python ./resources/keycloak_bootstrap.py
           cat KEYCLOAK_OIDC_URL.txt
           cat KEYCLOAK_CLIENT_ID.txt
@@ -231,7 +239,7 @@ jobs:
       - name: tests
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           export KEYCLOAK_OIDC_URL=$(cat KEYCLOAK_OIDC_URL.txt)
           echo $KEYCLOAK_OIDC_URL
           export KEYCLOAK_CLIENT_ID=$(cat KEYCLOAK_CLIENT_ID.txt)
@@ -264,7 +272,7 @@ jobs:
         if: always()
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           set -x
           cat ./broker.out
           if [ -n "$(ls -A ./broker_logs/ 2>/dev/null)" ]; then
@@ -276,14 +284,14 @@ jobs:
         if: always()
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker logs "${{ matrix.broker_client }}" || true
 
       - name: keycloak docker logs
         if: always() && matrix.broker_client == 'rabbitmq'
         run: |
           set -euo pipefail
-          echo "now: $(date --utc --iso-8601=seconds)"
+          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker logs $(docker ps -a --filter "ancestor=ghcr.io/wipacrepo/keycloak-rest-services:test-keycloak-master" --format "{{.Names}}" | head -n 1)
 
 
